name: Build Kernel

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Setup Clang Toolchain
        uses: kdrag0n/get-clang@v1

      - name: Remove Git metadata to fix kernel version (remove plus sign)
        run: |
          rm -rf .git
          echo "" > localversion

      - name: Build Kernel
        run: |
          export ARCH=arm64
          export SUBARCH=arm64
          export PATH="/opt/clang/bin:$PATH"
          
          # আপনার ফোনের সঠিক defconfig ফাইলের নাম এখানে বসাতে হবে (যেমন: rm6781_defconfig বা rmx3492_defconfig)
          make O=out CC=clang CROSS_COMPILE=aarch64-linux-gnu- apollo_defconfig
          make O=out CC=clang CROSS_COMPILE=aarch64-linux-gnu- -j$(nproc)
